apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: KafkaNodePool
      name: broker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/storage/type
        value: persistent-claim
      - op: add
        path: /spec/storage/size
        value: 100Gi
  - target:
      kind: KafkaNodePool
      name: controller
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/storage/type
        value: persistent-claim
      - op: add
        path: /spec/storage/size
        value: 100Gi
